# Generated by Django 5.0 on 2024-01-31 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(max_length=255, unique=True)),
                ('document_ids', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tokens', models.TextField()),
                ('abstract', models.TextField(null=True)),
                ('presentation_date', models.DateField(null=True)),
                ('presentation_place', models.TextField(max_length=255, null=True)),
                ('file_path', models.TextField(max_length=255)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=50)),
                ('number_cited', models.IntegerField(null=True)),
                ('number_downloaded', models.IntegerField(null=True)),
                ('indexed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.categories')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.documenttype')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.university')),
            ],
        ),
        migrations.CreateModel(
            name='TfidfValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_vectors', models.TextField()),
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.documents')),
            ],
        ),
    ]
