# Generated by Django 4.2.5 on 2023-11-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tokens', models.TextField()),
                ('abstract', models.TextField(null=True)),
                ('presentation_date', models.DateField(null=True)),
                ('presentation_place', models.TextField(max_length=255, null=True)),
                ('file_path', models.TextField(max_length=255)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=50)),
                ('number_cited', models.IntegerField(null=True)),
                ('number_downloaded', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.categories')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(max_length=255, unique=True)),
                ('document_ids', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TfidfValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_vectors', models.TextField()),
                ('document_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.documents')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.documenttype'),
        ),
    ]
