# Generated by Django 4.2.5 on 2024-01-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_documents_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.university'),
        ),
    ]
